name: Go Build and Run
on:
  workflow_dispatch:
  schedule:
    # Run hourly
    - cron: '0 * * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build the Go project
        run: go build -v ./...
      - name: Run the Go project
        env:
          SEATS_AERO_API_KEY: ${{ secrets.SEATS_AERO_API_KEY }}
        run: ./seatsaero search > trips.json

      - name: Decisions decisions
        run: |
          echo "Seeing if trip was available"
          if [ -f trips.json ] && [ $(cat trips.json | jq 'length') -gt 0 ]; then
            echo "trips.json contains elements in the array"
            echo "DOIT" >> $GITHUB_ENV
            DATE_TAG=$(date +'%Y%m%d%H%M%S')
            echo "RELEASE_TAG=v${DATE_TAG}" >> $GITHUB_ENV
            echo "RELEASE_TITLE=Release ${DATE_TAG}" >> $GITHUB_ENV
          else
            echo "trips.json does not contain elements in the array, wrapping up"
          fi

      - name: Upload trips result
        uses: actions/upload-artifact@v4
        with:
          name: trips
          path: trips.json

      - name: create release
        if: ${{ env.DOIT == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          body_path: trips.json
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          title: ${{ env.RELEASE_TITLE }}
